server:
  port: 8080
  servlet:
    context-path: /lemon
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testplatform?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 443321
    
logging:
  level:
    root: info
    com.lemon.mapper: trace